# Generated by Django 5.0.6 on 2024-08-07 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(default=0)),
                ('database', models.BooleanField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('email1', models.CharField(blank=True, max_length=20, null=True)),
                ('sms', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 7, 13, 27, 29, 70999)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 7, 13, 27, 29, 71461)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 7, 13, 27, 29, 69949)),
        ),
    ]
