# Generated by Django 5.0.6 on 2024-08-09 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 9, 58, 49, 576496)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 9, 58, 49, 576966)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 9, 58, 49, 575422)),
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
