# Generated by Django 5.0.6 on 2024-08-09 10:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.event'),
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 41, 19, 151446)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 41, 19, 151930)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 41, 19, 153735)),
        ),
    ]
