# Generated by Django 5.0.6 on 2024-08-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='var',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='var',
            name='database',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='var',
            name='email1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='var',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='var',
            name='sms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 42, 52, 981703)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 42, 52, 982189)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 42, 52, 983903)),
        ),
    ]
