# Generated by Django 5.0.6 on 2024-08-09 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_var_action_var_code_var_database_var_email1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='var',
            name='action',
        ),
        migrations.RemoveField(
            model_name='var',
            name='code',
        ),
        migrations.RemoveField(
            model_name='var',
            name='database',
        ),
        migrations.RemoveField(
            model_name='var',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='var',
            name='event',
        ),
        migrations.RemoveField(
            model_name='var',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='var',
            name='sms',
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 49, 26, 427656)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 49, 26, 428119)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 10, 49, 26, 426596)),
        ),
    ]
